[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM10
monitor_port = COM10

lib_deps = arduino-libraries/Servo