# -*- coding: utf-8 -*-
"""advrobotcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAo2owmCC6ol67IN9QJIVn0mQ6t9IkaM
"""

# Cell 1 - Install dependencies
!pip install roboflow ultralytics

from roboflow import Roboflow
rf = Roboflow(api_key="NK4xWRWvj76KitincTkk")
project = rf.workspace("sashwats-workspace").project("tool-detection-q8za1")
version = project.version(4)
dataset = version.download("yolov8")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=100,
    imgsz=320,
    batch=16,
    name="foam_tools_v3",
    patience=20
)

from google.colab import files
files.download('/content/runs/detect/foam_tools_v3/weights/best.pt')